using System.Runtime.InteropServices.JavaScript;
using System.Runtime.Versioning;

namespace RioEditor.Browser;

/// <summary>
/// Thin typed wrapper over <c>wwwroot/rio-interop.js</c>. All members are generated by the
/// JS-interop source generator, so there is no reflection and it survives trimming/AOT.
/// </summary>
[SupportedOSPlatform("browser")]
internal static partial class RioInterop
{
    private const string ModuleName = "rio";

    private static bool _initialized;

    public static async Task InitializeAsync()
    {
        if (_initialized)
        {
            return;
        }

        // Module URLs resolve relative to _framework/, so step up one level. This also keeps
        // the app working when it is deployed under a sub-path rather than at the site root.
        await JSHost.ImportAsync(ModuleName, "../rio-interop.js");
        _initialized = true;
    }

    [JSImport("registerMessageHandler", ModuleName)]
    internal static partial void RegisterMessageHandler(
        [JSMarshalAs<JSType.Function<JSType.String>>] Action<string> handler);

    [JSImport("loadHtml", ModuleName)]
    internal static partial void LoadHtml(string html);

    [JSImport("executeScript", ModuleName)]
    internal static partial bool ExecuteScript(string script);

    [JSImport("setBounds", ModuleName)]
    internal static partial void SetBounds(double x, double y, double width, double height);

    [JSImport("setVisible", ModuleName)]
    internal static partial void SetVisible(bool visible);

    [JSImport("isLoaded", ModuleName)]
    internal static partial bool IsLoaded();

    [JSImport("focusEditor", ModuleName)]
    internal static partial void FocusEditor();

    [JSImport("storageGet", ModuleName)]
    internal static partial string? StorageGet(string key);

    [JSImport("storageSet", ModuleName)]
    internal static partial void StorageSet(string key, string value);

    [JSImport("storageRemove", ModuleName)]
    internal static partial void StorageRemove(string key);

    [JSImport("downloadText", ModuleName)]
    internal static partial void DownloadText(string fileName, string text);
}
